export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART =  "REMOVE_ITEM_FROM_CART";
export const INCREASE_ITEM_AMOUNT_IN_CART = "INCREASE_ITEM_AMOUNT_IN_CART";
export const DECREASE_ITEM_AMOUNT_IN_CART = "DECREASE_ITEM_AMOUNT_IN_CART";
